import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHouse } from '@fortawesome/free-solid-svg-icons';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="text-3xl font-bold underline">Hello world!</h1>
				<FontAwesomeIcon icon={faHouse} className="w-10" />
			</main>
		</>
	);
}
